---
title: RESTEASY-2505工作笔记（三）
---

### org.jboss.resteasy.test.mapper.ExceptionHandlerTest

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/Class Diagram7.png)

### testWebApplicationException()

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/org.jboss.resteasy.test.mapper.ExceptionHandlerTest.testWebApplicationException().png)

### org.jboss.resteasy.spi.NoLogWebApplicationException

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/854F540A-30C8-413F-974B-E97779020BA3.png)

### javax.ws.rs.core.Response

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/3705197A-16B2-4719-A7EE-29C7A0A29AA5.png)

### /locating/basic

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/472DBCF0-8572-493C-99F8-CCA560B52EE6.png)

上面这个URL无所谓怎么写，因为是`MockHttpRequest`。 

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/7D88C8E3-66DA-4F82-AB10-20A93380C446.png)

上面这个是直接调用了`ExceptionHandler`的`handleException()`方法。真正的使用位置是`SynchronousDispatcher`里面：

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun04/6A39CBC6-FAE3-4A39-A957-FD2C7B3CB545.png)
